GET http://ec2-54-91-59-31.compute-1.amazonaws.com:8000/api/chords/29

POST http://ec2-54-91-59-31.compute-1.amazonaws.com:8000/analyze-frame
{
  
  "chord": {
    "name": "c",
    "type": "major",
    "tab": ["2", "3", "2", "0", "X", "X"],

  }
}